name: Build and Download Tink for iOS

on:
  push:
    branches:
      - main

env:
  XCODE_PRODUCT_NAME: Tink
  XCODE_SCHEME: Tink
  IPHONEOS_DEPLOYMENT_TARGET: 14.0
  SIMULATOR_DEPLOYMENT_TARGET: 14.0

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install cmake openssl
          cmake -Bbuild -H. \
              -DTINK_BUILD_SHARED_LIBRARIES=OFF \
              -DTINK_PLATFORM=IOS \
              -DTINK_BUILD_GFLAGS=OFF
          make -C build -j $(sysctl -n hw.logicalcpu) install

      - name: Create xcframework
        run: |
          cd build/lib/ios
          xcodebuild -create-xcframework \
               -library tink.framework \
               -output tink.xcframework

      - name: Download xcframework
        uses: actions/download-artifact@v3
        with:
          name: tink-ios-xcframework
          path: /output
