name: Compile Tink C++ for iOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v1

      - name: Install Xcode command line tools
        run: xcode-select --install

      - name: Install dependencies
        run: brew install automake libtool

      - name: Configure Tink
        run: ./configure

      - name: Compile Tink for iOS
        run: bazel build --config=ios //...

      - name: Archive artifacts
        run: |
          mkdir artifacts
          cp -r bazel-bin/* artifacts/
          zip -r artifacts.zip artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tink-ios-artifacts
          path: artifacts.zip
