name: Compile Tink C++ for iOS

on: [push]

jobs:
 build:
   runs-on: macos-latest

   steps:
   - name: Checkout repository
     uses: actions/checkout@v2

   - name: Set up Bazel
     run: |
       git clone https://github.com/tink-crypto/tink.git
       cd tink
       mkdir build
       cd build
       cmake .. -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_INSTALL_PREFIX=/path/to/install/directory \
        -DTINK_BUILD_TOOLS=OFF 
       ls
