name: Compile Tink C++ for iOS
on: [push]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Install dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y git cmake ninja-build clang

     - name: Download Tink
       run: |
         wget https://github.com/tink-crypto/tink-cc/archive/refs/tags/v2.1.1.zip
         unzip v2.1.1.zip

     - name: Compile Tink
       run: |
         cd tink-cc-2.1.1
         mkdir build && cd build
         cmake ..
         make