name: Build Tink for iOS

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bazel
      uses: bazelbuild/setup-bazelisk@v3

    - name: Set up environment
      run: |
        export XCODE_VERSION=9.2
        export IOS_SDK=11.2

    - name: Clone Tink repository
      run: git clone https://github.com/google/tink/

    - name: Change to Tink directory
      run: cd tink

    - name: Build Tink for iOS
      run: |
        bazel build -c opt --ios_multi_cpus=i386,x86_64,armv7,arm64 --xcode_version="${XCODE_VERSION}" --ios_sdk_version="${IOS_SDK}" //objc:Tink_framework
